import { execFileSync, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { load as loadYaml } from "js-yaml";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";

interface WorkflowStep {
  id?: string;
  name?: string;
  run?: string;
  uses?: string;
  if?: string;
  env?: Record<string, string>;
  with?: Record<string, unknown>;
}

interface UpdateWorkflow {
  name: string;
  on: {
    schedule: Array<{ cron: string }>;
    workflow_dispatch: null;
  };
  permissions: Record<string, string>;
  concurrency?: unknown;
  jobs: {
    "update-patterns": {
      "runs-on": string;
      steps: WorkflowStep[];
    };
  };
}

const workflowSource = readFileSync(
  new URL("../.github/workflows/update-patterns.yml", import.meta.url),
  "utf8",
);
const workflow = loadYaml(workflowSource) as UpdateWorkflow;
const steps = workflow.jobs["update-patterns"].steps;
const step = (name: string): WorkflowStep => {
  const found = steps.find((candidate) => candidate.name === name);
  if (!found) throw new Error(`Missing workflow step: ${name}`);
  return found;
};
const runStep = (name: string): string => step(name).run ?? "";

function runShell(
  script: string,
  env: NodeJS.ProcessEnv,
  cwd?: string,
  input?: string,
): { status: number; stdout: string; stderr: string } {
  const result = spawnSync("bash", ["--noprofile", "--norc", "-eo", "pipefail", "-c", script], {
    cwd,
    env,
    encoding: "utf8",
    input,
    stdio: [input === undefined ? "ignore" : "pipe", "pipe", "pipe"],
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

function isolatedTemp(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

function git(args: string[], cwd: string, env: NodeJS.ProcessEnv = {}): string {
  return execFileSync("git", args, {
    cwd,
    env: { ...process.env, ...env },
    encoding: "utf8",
  });
}

function outputValues(output: string): Record<string, string> {
  return Object.fromEntries(
    output
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => {
        const separator = line.indexOf("=");
        return [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

function fixtureGeneratedSource(updated: string, rules = "2"): string {
  return [
    "// AUTO-GENERATED by scripts/update-gitleaks-patterns.ts — do not edit manually",
    "// Source: fixture",
    `// Updated: ${updated}`,
    `// Rules: ${rules} (0 skipped — none)`,
    "",
    "export const GITLEAKS_PATTERNS = [",
    "  { id: 'fixture', flags: '', regex: 'fixture', description: 'fixture' },",
    "];",
    "",
  ].join("\n");
}

describe("update-patterns workflow", () => {
  it("keeps the scheduled/manual trigger, permissions, runner, and exact step order", () => {
    expect(workflow.name).toBe("Update Gitleaks Patterns");
    expect(workflow.on.schedule).toEqual([{ cron: "0 6 * * 1" }]);
    expect(workflow.on.workflow_dispatch).toBeNull();
    expect(workflow.permissions).toEqual({ contents: "read", "pull-requests": "read" });
    expect(workflow.concurrency).toBeUndefined();
    expect(workflow.jobs["update-patterns"]["runs-on"]).toBe("ubuntu-latest");
    expect(steps.map(({ name }) => name)).toEqual([
      "Checkout main",
      "Require pattern bot token",
      "Setup Node",
      "Bootstrap verified pnpm",
      "Locate pnpm store",
      "Cache pnpm store",
      "Install dependencies",
      "Run update-gitleaks-patterns",
      "Check for changes",
      "Validate rule count",
      "Write changeset",
      "Commit and open PR",
      "Summary",
      "No-op summary",
    ]);
  });

  it("uses the pinned checkout/setup actions and exact checkout inputs", () => {
    expect(step("Checkout main")).toEqual({
      name: "Checkout main",
      uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1",
      with: {
        ref: "main",
        token: "${{ github.token }}",
        "persist-credentials": false,
        "fetch-depth": 0,
      },
    });
    expect(step("Setup Node")).toMatchObject({
      uses: "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020",
      with: { "node-version": "22.20.0" },
    });
  });

  it("bootstraps pnpm before resolving the exact store cache and frozen install", () => {
    expect(runStep("Bootstrap verified pnpm")).toContain('mktemp -d "$RUNNER_TEMP/lcm-pnpm.XXXXXX"');
    expect(runStep("Bootstrap verified pnpm")).toContain(
      'node scripts/bootstrap-pnpm.mjs --destination "$bootstrap_root/pnpm"',
    );
    expect(runStep("Bootstrap verified pnpm")).toContain('"$pnpm_bin" >> "$GITHUB_PATH"');
    expect(runStep("Bootstrap verified pnpm")).toContain("npm_config_store_dir=%s");
    expect(runStep("Bootstrap verified pnpm")).toContain('"$RUNNER_TEMP/lcm-pnpm-store" >> "$GITHUB_ENV"');
    expect(runStep("Locate pnpm store")).toContain('store_path="$(pnpm store path)"');
    expect(step("Cache pnpm store")).toMatchObject({
      uses: "actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306",
      with: {
        path: "${{ steps.pnpm-store.outputs.path }}",
        key: "pnpm-store-v1-${{ runner.os }}-${{ runner.arch }}-node-22.20.0-${{ hashFiles('package.json', 'pnpm-lock.yaml', '.npmrc', 'pnpm-workspace.yaml', 'scripts/bootstrap-pnpm.mjs') }}",
      },
    });
    expect(step("Cache pnpm store").with).not.toHaveProperty("restore-keys");
    expect(runStep("Install dependencies")).toBe("pnpm install --frozen-lockfile");
    expect(step("Install dependencies").if).toBeUndefined();
    expect(workflowSource).not.toMatch(/\bnpm (?:ci|run)|\bnpx\b/u);
  });

  it("runs the token preflight before setup/install/generator and fails clearly when PAT is absent", () => {
    const preflight = runStep("Require pattern bot token");
    const checkoutIndex = steps.findIndex(({ name }) => name === "Checkout main");
    const preflightIndex = steps.findIndex(({ name }) => name === "Require pattern bot token");
    expect(preflightIndex).toBe(checkoutIndex + 1);
    for (const later of [
      "Setup Node",
      "Bootstrap verified pnpm",
      "Locate pnpm store",
      "Cache pnpm store",
      "Install dependencies",
      "Run update-gitleaks-patterns",
      "Check for changes",
      "Validate rule count",
      "Write changeset",
      "Commit and open PR",
      "Summary",
      "No-op summary",
    ]) {
      expect(preflightIndex).toBeLessThan(steps.findIndex(({ name }) => name === later));
    }
    const missingOutputRoot = isolatedTemp("lcm-patterns-output-");
    const missing = runShell(preflight, {
      ...process.env,
      PATTERNS_BOT_TOKEN: "",
      GITHUB_OUTPUT: join(missingOutputRoot, "output"),
    });
    expect(missing.status).toBe(1);
    expect(missing.stderr + missing.stdout).toContain(
      "::error::PATTERNS_BOT_TOKEN is required so generated PRs trigger normal pull_request checks.",
    );
    const fixtureToken = "fixture-pattern-token";
    const configuredOutputRoot = isolatedTemp("lcm-patterns-output-");
    const configured = runShell(preflight, {
      ...process.env,
      PATTERNS_BOT_TOKEN: fixtureToken,
      GITHUB_OUTPUT: join(configuredOutputRoot, "output"),
    });
    expect(configured.status).toBe(0);
    expect(configured.stdout + configured.stderr).not.toContain(fixtureToken);
    rmSync(missingOutputRoot, { force: true, recursive: true });
    rmSync(configuredOutputRoot, { force: true, recursive: true });
  });

  it("executes the actual change check with timestamp-only no-op and semantic-change behavior", () => {
    const check = runStep("Check for changes");
    expect(check).toContain("git diff --quiet --ignore-matching-lines='^// Updated:' -- src/generated-patterns.ts");
    expect(check).toContain("git restore src/generated-patterns.ts");
    expect(check).toContain("changed=false");
    expect(check).toContain("changed=true");
    expect(check).toContain("rule_count=$count");

    const cases = [
      {
        name: "timestamp-only header replacement",
        before: fixtureGeneratedSource("2026-01-01T00:00:00.000Z"),
        after: fixtureGeneratedSource("2026-01-02T00:00:00.000Z"),
        expectedChanged: "false",
        expectedCount: undefined,
      },
      {
        name: "timestamp and adjacent Rules count change",
        before: fixtureGeneratedSource("2026-01-01T00:00:00.000Z", "2"),
        after: fixtureGeneratedSource("2026-01-02T00:00:00.000Z", "3"),
        expectedChanged: "true",
        expectedCount: "3",
      },
      {
        name: "timestamp and distant rule-body change with stable count",
        before: fixtureGeneratedSource("2026-01-01T00:00:00.000Z", "2"),
        after: fixtureGeneratedSource("2026-01-02T00:00:00.000Z", "2").replace(
          "description: 'fixture'",
          "description: 'changed fixture'",
        ),
        expectedChanged: "true",
        expectedCount: "2",
      },
    ];

    for (const testCase of cases) {
      const root = isolatedTemp("lcm-patterns-diff-");
      const sourcePath = join(root, "src", "generated-patterns.ts");
      const outputPath = join(dirname(root), `${root.split("/").pop()}-github-output`);
      mkdirSync(dirname(sourcePath), { recursive: true });
      writeFileSync(sourcePath, testCase.before);
      git(["init", "-q"], root);
      git(["config", "user.email", "fixture@example.test"], root);
      git(["config", "user.name", "fixture"], root);
      git(["add", "src/generated-patterns.ts"], root);
      git(["commit", "-qm", "fixture"], root);
      writeFileSync(sourcePath, testCase.after);
      const result = runShell(check, {
        ...process.env,
        GITHUB_OUTPUT: outputPath,
      }, root);
      expect(result.status, testCase.name).toBe(0);
      const outputs = outputValues(readFileSync(outputPath, "utf8"));
      expect(outputs.changed, testCase.name).toBe(testCase.expectedChanged);
      if (testCase.expectedCount) expect(outputs.rule_count, testCase.name).toBe(testCase.expectedCount);
      if (testCase.expectedChanged === "false") {
        expect(readFileSync(sourcePath, "utf8")).toBe(testCase.before);
        expect(git(["status", "--short"], root)).toBe("");
        expect(result.stdout).toContain("No changes to generated-patterns.ts");
      } else {
        expect(readFileSync(sourcePath, "utf8")).toBe(testCase.after);
        expect(git(["status", "--short"], root)).toContain(" M src/generated-patterns.ts");
      }
      rmSync(outputPath, { force: true });
      rmSync(root, { force: true, recursive: true });
    }

    expect(step("Validate rule count").if).toBe("steps.diff.outputs.changed == 'true'");
    expect(step("Write changeset").if).toBe("steps.diff.outputs.changed == 'true'");
    expect(step("Commit and open PR").if).toBe("steps.diff.outputs.changed == 'true'");
    expect(step("Summary").if).toBe("steps.diff.outputs.changed == 'true'");
    expect(step("No-op summary").if).toBe("steps.diff.outputs.changed == 'false'");
  });

  it("preserves generator ordering, checksum-pinned invocation, and publication metadata", () => {
    const names = steps.map(({ name }) => name);
    expect(names.indexOf("Run update-gitleaks-patterns")).toBeLessThan(names.indexOf("Check for changes"));
    expect(runStep("Run update-gitleaks-patterns")).toBe(
      "pnpm run update:patterns",
    );
    const commit = runStep("Commit and open PR");
    expect(commit).toContain("git commit -s");
    expect(commit).toContain("git commit -s -m");
    expect(commit).not.toContain("--gpg-sign");
    const publicationStart = commit.indexOf("git add src/generated-patterns.ts");
    const publicationEnd = commit.indexOf("\nGIT_TERMINAL_PROMPT", publicationStart);
    expect(publicationStart).toBeGreaterThanOrEqual(0);
    expect(publicationEnd).toBeGreaterThan(publicationStart);
    const publicationCommit = commit.slice(publicationStart, publicationEnd);
    const dcoRoot = isolatedTemp("lcm-patterns-dco-");
    mkdirSync(join(dcoRoot, "src"), { recursive: true });
    mkdirSync(join(dcoRoot, ".changeset"), { recursive: true });
    writeFileSync(join(dcoRoot, "src", "generated-patterns.ts"), "fixture\n");
    writeFileSync(join(dcoRoot, ".changeset", "gitleaks-patterns-2.md"), "fixture\n");
    git(["init", "-q"], dcoRoot);
    git(["config", "user.name", "fixture"], dcoRoot);
    git(["config", "user.email", "fixture@example.test"], dcoRoot);
    const published = runShell(publicationCommit, {
      ...process.env,
      RULE_COUNT: "2",
      CHANGESET: ".changeset/gitleaks-patterns-2.md",
    }, dcoRoot);
    expect(published.status).toBe(0);
    const publishedMessage = git(["log", "-1", "--format=%B"], dcoRoot);
    expect((publishedMessage.match(/^Signed-off-by:/gm) ?? []).length).toBe(1);
    rmSync(dcoRoot, { force: true, recursive: true });
    expect(commit).toContain("push -u origin \"$BRANCH\" --force-with-lease");
    expect(commit).toContain('gh pr list');
    expect(commit).toContain('gh pr create');
    expect(commit).toContain('--base main');
    expect(commit).toContain('--head "$BRANCH"');
    expect(commit).toContain('chore(security): sync gitleaks patterns');
    expect(commit).toContain('"$CHANGESET"');
    expect(runStep("Write changeset")).toContain(
      'gitleaks-patterns-${RULE_COUNT}.md',
    );
    expect(runStep("Write changeset")).toContain(
      "Update generated gitleaks redaction patterns to ${RULE_COUNT} rules.",
    );
  });

  it("enforces the exact two-file allowlist and rejects unrelated drift", () => {
    const commit = runStep("Commit and open PR");
    const allowlistStart = commit.indexOf("UNEXPECTED=$(git status --short");
    const allowlistEnd = commit.indexOf("\n\ngit add", allowlistStart);
    expect(allowlistStart).toBeGreaterThanOrEqual(0);
    expect(allowlistEnd).toBeGreaterThan(allowlistStart);
    const allowlist = commit.slice(allowlistStart, allowlistEnd);
    const runAllowlist = (files: string[]): { status: number; output: string } => {
      const root = isolatedTemp("lcm-patterns-allowlist-");
      git(["init", "-q"], root);
      for (const file of files) {
        const path = join(root, file);
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, "fixture\n");
      }
      if (files.includes(".changeset/gitleaks-patterns-2.md")) {
        writeFileSync(join(root, ".changeset", ".gitkeep"), "fixture\n");
      }
      git(["config", "user.name", "fixture"], root);
      git(["config", "user.email", "fixture@example.test"], root);
      git(
        ["add", "src/generated-patterns.ts", ...(files.includes(".changeset/gitleaks-patterns-2.md") ? [".changeset/.gitkeep"] : [])],
        root,
      );
      git(["commit", "-qm", "fixture"], root);
      writeFileSync(join(root, "src", "generated-patterns.ts"), "changed\n");
      if (files.includes(".changeset/gitleaks-patterns-2.md")) {
        writeFileSync(join(root, ".changeset/gitleaks-patterns-2.md"), "changed\n");
      }
      const result = runShell(`set -e\n${allowlist}`, { ...process.env }, root);
      rmSync(root, { force: true, recursive: true });
      return { status: result.status, output: result.stdout + result.stderr };
    };
    expect(runAllowlist(["src/generated-patterns.ts", ".changeset/gitleaks-patterns-2.md"]).status).toBe(0);
    expect(runAllowlist(["src/generated-patterns.ts", ".changeset/gitleaks-patterns-2.md", "README.md"]).output).toContain(
      "::error::Pattern update produced changes outside the allowlist",
    );
  });

  it("separates checkout github.token from PAT publication auth and forbids tokenized remotes", () => {
    const checkout = step("Checkout main");
    expect(checkout.with?.token).toBe("${{ github.token }}");
    expect(step("Require pattern bot token").env?.PATTERNS_BOT_TOKEN).toBe(
      "${{ secrets.PATTERNS_BOT_TOKEN }}",
    );
    expect(step("Commit and open PR").env).toEqual({
      GH_TOKEN: "${{ secrets.PATTERNS_BOT_TOKEN }}",
      GH_PROMPT_DISABLED: "1",
    });
    const compactWorkflow = workflowSource.replace(/\s+/g, "");
    expect((compactWorkflow.match(/\$\{\{secrets\.PATTERNS_BOT_TOKEN\}\}/g) ?? []).length).toBe(2);
    for (const forbidden of [
      "x-access-token",
      "git remote set-url",
      "gh auth setup-git",
      "credential.helper store",
      "credential-cache",
      "${GH_TOKEN}",
    ]) {
      expect(workflowSource).not.toContain(forbidden);
    }
    expect(workflowSource).not.toMatch(/https:\/\/[^\n]*\$\{?GH_TOKEN/);
    expect(workflowSource).not.toMatch(/\$\{\{[^}]*TOKEN[^}]*\}\}[^\n]*https:\/\//);
    expect(workflowSource).not.toMatch(/\|\|\s*true/);
  });

  it("uses prompt-disabled exact helper for ls-remote, conditional fetch, and push", () => {
    const commit = runStep("Commit and open PR");
    const helper = "GIT_TERMINAL_PROMPT=0 git -c credential.helper= -c 'credential.helper=!gh auth git-credential'";
    expect(commit).toContain(`${helper} ls-remote --exit-code --refs origin "refs/heads/$BRANCH" >/dev/null`);
    expect(commit).toContain(`${helper} fetch origin "refs/heads/$BRANCH:refs/remotes/origin/$BRANCH"`);
    expect(commit).toContain(`${helper} push -u origin "$BRANCH" --force-with-lease`);
    expect(commit).toContain("branch_status=$?");
    expect(commit).toContain('if [[ "$branch_status" -eq 0 ]]');
    expect(commit).toContain('elif [[ "$branch_status" -eq 2 ]]');
    expect(commit).toContain("Existing branch discovery failed");
    expect(commit.indexOf(`${helper} fetch`)).toBeLessThan(commit.indexOf(`${helper} push`));
    expect(commit).not.toContain("git fetch origin \"$BRANCH:refs/remotes/origin/$BRANCH\" ||");
  });

  it("dispatches existing, absent, and failed branch discovery using the actual workflow fragment", () => {
    const commit = runStep("Commit and open PR");
    const discoveryStart = commit.indexOf("set +e");
    const discoveryEnd = commit.indexOf("\n\nGENERATED_COPY", discoveryStart);
    expect(discoveryStart).toBeGreaterThanOrEqual(0);
    expect(discoveryEnd).toBeGreaterThan(discoveryStart);
    const discovery = commit.slice(discoveryStart, discoveryEnd);
    const remote = isolatedTemp("lcm-patterns-remote-");
    const local = isolatedTemp("lcm-patterns-branch-");
    git(["init", "--bare", "-q", remote], dirname(remote));
    git(["init", "-q"], local);
    git(["config", "user.name", "fixture"], local);
    git(["config", "user.email", "fixture@example.test"], local);
    writeFileSync(join(local, "fixture.txt"), "fixture\n");
    git(["add", "fixture.txt"], local);
    git(["commit", "-qm", "fixture"], local);
    git(["remote", "add", "origin", remote], local);
    const branch = "chore/fixture-patterns";
    git(["branch", "-M", branch], local);
    git(["push", "-q", "origin", branch], local);

    const runDiscovery = (): { status: number; stdout: string; stderr: string } =>
      runShell(discovery, { ...process.env, BRANCH: branch }, local);
    const existing = runDiscovery();
    expect(existing.status).toBe(0);
    expect(git(["rev-parse", `refs/remotes/origin/${branch}`], local).trim()).toBe(
      git(["rev-parse", branch], local).trim(),
    );

    const absentBranch = "chore/absent-patterns";
    const absent = runShell(discovery, { ...process.env, BRANCH: absentBranch }, local);
    expect(absent.status).toBe(0);
    expect(absent.stdout).toContain(`No existing remote branch found; push will create ${absentBranch}.`);
    expect(
      runShell(`git show-ref --verify refs/remotes/origin/${absentBranch}`, { ...process.env }, local).status,
    ).not.toBe(0);

    const bad = isolatedTemp("lcm-patterns-bad-remote-");
    git(["init", "-q"], bad);
    git(["remote", "add", "origin", join(bad, "missing.git")], bad);
    const failed = runShell(discovery, { ...process.env, BRANCH: branch }, bad);
    expect(failed.status).not.toBe(0);
    expect(failed.stdout + failed.stderr).toContain("::error::Existing branch discovery failed with status");
    rmSync(remote, { force: true, recursive: true });
    rmSync(local, { force: true, recursive: true });
    rmSync(bad, { force: true, recursive: true });
  });

  it("proves real gh credential resolution is network-free and leaves no token/config persistence", () => {
    const which = runShell("command -v gh || { echo 'gh CLI is required for credential helper contract' >&2; exit 1; }", {
      ...process.env,
    });
    expect(which.status).toBe(0);
    const root = isolatedTemp("lcm-patterns-credential-");
    const globalConfig = join(root, "gitconfig");
    const ghConfig = join(root, "gh");
    const xdgState = join(root, "xdg");
    mkdirSync(ghConfig);
    mkdirSync(xdgState);
    git(["init", "-q"], root, { GIT_CONFIG_GLOBAL: globalConfig });
    const localConfig = join(root, ".git", "config");
    writeFileSync(globalConfig, "[user]\n\temail = fixture@example.test\n");
    const hash = (path: string): string => createHash("sha256").update(readFileSync(path)).digest("hex");
    const localBefore = hash(localConfig);
    const globalBefore = hash(globalConfig);
    const fixtureToken = "fixture-credential-token";
    const result = runShell(
      "set -e\nGIT_TERMINAL_PROMPT=0 git -c credential.helper= -c 'credential.helper=!gh auth git-credential' credential fill",
      {
        ...process.env,
        GH_TOKEN: fixtureToken,
        GITHUB_TOKEN: "",
        GIT_CONFIG_GLOBAL: globalConfig,
        GIT_CONFIG_NOSYSTEM: "1",
        GH_CONFIG_DIR: ghConfig,
        XDG_STATE_HOME: xdgState,
        GH_NO_UPDATE_NOTIFIER: "1",
        GH_NO_EXTENSION_UPDATE_NOTIFIER: "1",
        GH_TELEMETRY: "0",
        GH_PROMPT_DISABLED: "1",
        GIT_TERMINAL_PROMPT: "0",
        HTTP_PROXY: "http://127.0.0.1:1",
        HTTPS_PROXY: "http://127.0.0.1:1",
        ALL_PROXY: "http://127.0.0.1:1",
        NO_PROXY: "",
      },
      root,
      "protocol=https\nhost=github.com\n\n",
    );
    expect(result.status).toBe(0);
    const values = outputValues(result.stdout);
    expect(values.username).toBe("x-access-token");
    expect(values.password).toBe(fixtureToken);
    expect(hash(localConfig)).toBe(localBefore);
    expect(hash(globalConfig)).toBe(globalBefore);
    expect(readFileSync(globalConfig, "utf8")).not.toContain("password");
    const persisted = [ghConfig, xdgState].flatMap((path) => {
      if (!existsSync(path)) return [];
      return execFileSync("find", [path, "-type", "f", "-print"], { encoding: "utf8" })
        .trim()
        .split("\n")
        .filter(Boolean);
    });
    for (const path of persisted) expect(readFileSync(path, "utf8")).not.toContain(fixtureToken);
    rmSync(root, { force: true, recursive: true });
  });
});
