import { beforeAll, describe, expect, it } from "vitest";
import { Command } from "commander";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  CLI_SCENARIO_PATHS,
  FAULT_ASSERTION_OWNERS,
  assertMatrixMatches,
  discoverInventory,
  discoverCli,
  inspectCommanderTree,
  extractNativeImportProviders,
  extractCustomHelpGrammar,
  extractPortableExports,
  extractSensitiveOperations,
  matrixPath,
  renderMatrix,
  scenarioMap,
  type DiscoveredSurface,
  type SurfaceRow,
} from "../../surface-parity/inventory.js";

let discovered: DiscoveredSurface[];
let matrix: SurfaceRow[];

beforeAll(async () => {
  discovered = await discoverInventory();
  const rendered = renderMatrix(discovered, scenarioMap);
  if (process.env.LCM_SURFACE_MATRIX_UPDATE === "1") writeFileSync(matrixPath, rendered);
  matrix = JSON.parse(readFileSync(matrixPath, "utf8"));
}, 120_000);

describe("complete public backend surface inventory", () => {
  it("equals real discovery exactly, including registration fingerprints and generated bytes", () => {
    expect(new Set(discovered.map((row) => row.id)).size).toBe(discovered.length);
    expect(new Set(matrix.map((row) => row.id)).size).toBe(matrix.length);
    expect(matrix.map((row) => row.id).sort()).toEqual(discovered.map((row) => row.id).sort());
    assertMatrixMatches(discovered, matrix);
    expect(readFileSync(matrixPath, "utf8")).toBe(renderMatrix(discovered, scenarioMap));
  });

  it("assigns every CLI path to one exclusive owner, including sensitive operations and root", () => {
    const ownership = Object.values(CLI_SCENARIO_PATHS).flat();
    expect(new Set(ownership).size).toBe(ownership.length);
    expect(ownership.map((path) => `cli:${path}`).sort()).toEqual(
      discovered.filter((row) => row.kind === "cli").map((row) => row.id).sort(),
    );
    expect(CLI_SCENARIO_PATHS.control).toHaveLength(20);
    expect(ownership).toHaveLength(60);
    expect(discovered.filter((row) => row.kind === "portable-domain")).toHaveLength(22);
    expect(discovered.find((row) => row.id === "daemon:POST /status")).toBeDefined();
    expect(discovered.find((row) => row.id === "daemon:GET /health")).toBeDefined();
    expect(discovered.find((row) => row.id === "daemon:GET /health/observe")).toBeDefined();
  });

  it.each(["add", "remove", "duplicate"])("rejects %s registration drift", (mutation) => {
    const changed = structuredClone(discovered);
    if (mutation === "add") changed.push({ ...changed[0], id: "cli:unclassified" });
    if (mutation === "remove") changed.shift();
    if (mutation === "duplicate") changed.push(changed[0]);
    expect(() => assertMatrixMatches(changed, matrix)).toThrow();
    expect(() => renderMatrix(changed, scenarioMap)).toThrow();
  });

  it.each([
    ["cli:search", "options"],
    ["mcp:lcm_search", "inputSchema"],
    ["daemon:POST /store", "admission"],
    ["daemon:POST /store", "publicationMode"],
    ["portable-domain:messages", "schemaSha256"],
  ])("rejects %s %s drift", (id, field) => {
    const changed = structuredClone(discovered);
    const row = changed.find((entry) => entry.id === id)!;
    if (field === "options") {
      const options = row.registration.options as Array<Record<string, unknown>>;
      options[0].flags = "--changed-option <value>";
    } else if (field === "inputSchema") {
      (row.registration.inputSchema as Record<string, unknown>).required = ["new-required-field"];
    } else row.registration[field] = "changed-contract";
    expect(() => assertMatrixMatches(changed, matrix)).toThrow();
  });

  it("requires one parse observation and restores the real parser even after failures", async () => {
    const original = Command.prototype.parseAsync;
    await discoverCli();
    expect(Command.prototype.parseAsync).toBe(original);
    await expect(discoverCli(async () => {})).rejects.toThrow("exactly once");
    expect(Command.prototype.parseAsync).toBe(original);
    await expect(discoverCli(async () => {
      await new Command().parseAsync();
      await new Command().parseAsync();
    })).rejects.toThrow("exactly once");
    expect(Command.prototype.parseAsync).toBe(original);
    await expect(discoverCli(async () => { throw new Error("observer-fixture"); })).rejects.toThrow("observer-fixture");
    expect(Command.prototype.parseAsync).toBe(original);
  });

  it("traverses parent links and records command aliases, argument and option contracts", () => {
    const root = new Command("lcm");
    const group = root.command("group");
    group.command("operation <input>").alias("op").option("--limit <value>", "limit", "2").action(() => {});
    const rows = inspectCommanderTree(root);
    expect(rows.map((row) => row.id)).toEqual(["cli:<root>", "cli:group", "cli:group operation"]);
    expect(rows[2].registration).toMatchObject({ aliases: ["op"], handler: true, arguments: [{ name: "input", required: true }], options: [{ flags: "--limit <value>", default: "2", required: true }] });
    group.commands[0].parent = root;
    expect(() => inspectCommanderTree(root)).toThrow("Detached");
  });

  it.each(["cli:sensitive purge", "portable-domain:passive-events"])("rejects missing %s without discarding extras", (id) => {
    expect(() => assertMatrixMatches(discovered.filter((row) => row.id !== id), matrix)).toThrow();
  });

  it("rejects missing, duplicate, unknown and assertion-free manifest ownership", () => {
    expect(() => assertMatrixMatches(discovered, matrix.slice(1))).toThrow();
    expect(() => assertMatrixMatches(discovered, [...matrix, matrix[0]])).toThrow();
    expect(() => assertMatrixMatches(discovered, [...matrix, { ...matrix[0], id: "cli:unknown" }])).toThrow();
    expect(() => renderMatrix(discovered, { ...scenarioMap, [matrix[0].id]: { ...scenarioMap[matrix[0].id], assertions: [] } })).toThrow();
    expect(() => renderMatrix(discovered, { ...scenarioMap, "cli:unknown": scenarioMap[matrix[0].id] })).toThrow();
  });

  it("extracts only the exported sensitive dispatch and fails closed on ambiguous or nonliteral cases", () => {
    const source = readFileSync(new URL("../../../src/sensitive.ts", import.meta.url), "utf8");
    expect(extractSensitiveOperations(source)).toEqual(["list", "add", "remove", "test", "purge"]);
    const missing = extractSensitiveOperations(source.replace(/    case "purge": \{[\s\S]*?\n    \}/, ""));
    expect(missing).not.toContain("purge");
    const withoutOperations = discovered.filter((row) => !(row.id.startsWith("cli:sensitive ")));
    const mutated = [...withoutOperations, ...missing.map((operation) => discovered.find((row) => row.id === `cli:sensitive ${operation}`)!)];
    expect(() => assertMatrixMatches(mutated, matrix)).toThrow();
    expect(() => extractSensitiveOperations(source.replace('case "purge":', "case dynamic:"))).toThrow();
    expect(() => extractSensitiveOperations(source.replace("switch (sub)", "switch (argv[1])"))).toThrow();
    expect(() => extractSensitiveOperations(source.replace("switch (sub)", "switch (sub) {} switch (sub)"))).toThrow();
    expect(() => extractSensitiveOperations(source.replace("export async function handleSensitive", "async function handleSensitive"))).toThrow();
  });

  it("binds the native import provider union to actual dispatch branches", () => {
    const source = readFileSync(new URL("../../../src/import.ts", import.meta.url), "utf8");
    expect(extractNativeImportProviders(source).providers).toEqual(["claude", "codex", "all"]);
    expect(() => extractNativeImportProviders(source.replace('"claude" | "codex" | "all"', '"claude" | "codex" | "all" | "new"'))).toThrow();
    expect(() => extractNativeImportProviders(source.replace('provider === "codex"', 'provider === "new"'))).toThrow();
  });

  it("enumerates public runtime exports separately from declarations and fails closed on export stars", () => {
    const source = readFileSync(new URL("../../../src/storage/portable.ts", import.meta.url), "utf8");
    const exports = extractPortableExports(source);
    expect(exports.runtime.map((entry) => entry.name)).toContain("createPostgreSqlPortableSource");
    expect(exports.declarations.map((entry) => entry.name)).toContain("StorageIdentityContext");
    expect(exports.runtime.map((entry) => entry.name)).not.toContain("StorageIdentityContext");
    const added = extractPortableExports(`${source}\nexport const newConsumerApi = () => {};\n`);
    expect(added.runtime.map((entry) => entry.name)).toContain("newConsumerApi");
    expect(() => renderMatrix([...discovered, {
      id: "portable-api:newConsumerApi", kind: "portable-api", source: "src/storage/portable.ts", registration: { ...added.runtime.find((entry) => entry.name === "newConsumerApi")! },
    }], scenarioMap)).toThrow();
    expect(() => extractPortableExports(`${source}\nexport * from './new.js';\n`)).toThrow();
  });

  it("distinguishes active health readiness from read-only statistical snapshots", () => {
    const health = matrix.find((row) => row.id === "daemon:GET /health")!;
    expect(health.architectureReason).toContain("active storage readiness");
    expect(health.architectureReason).toContain("Public unauthenticated health is liveness only");
    const observation = matrix.find((row) => row.id === "daemon:GET /health/observe")!;
    expect(observation.assertions).toEqual(["admission", "result", "effects"]);
    expect(observation.architectureReason).toContain("process identity only");
    expect(observation.architectureReason).toContain("storage status unverified");
    expect(observation.architectureReason).toContain("strict read-only contract");
    expect(matrix.find((row) => row.id === "daemon:GET /stats")!.architectureReason)
      .toContain("read-only contract");
  });

  it("assigns each fault variant once to an existing public row and requires its assertion", () => {
    const variants = Object.values(FAULT_ASSERTION_OWNERS).flat();
    expect(new Set(variants.map(({ id, assertion }) => `${id}:${assertion}`)).size).toBe(variants.length);
    for (const { id, assertion } of variants) {
      expect(matrix.find((row) => row.id === id)!.assertions).toContain(assertion);
      expect(matrix.find((row) => row.id === id)!.architectureReason).toContain("counterpart");
    }
  });

  it("projects every declared backend-denial assertion into the fault-denial scenario", () => {
    const declared = matrix.filter((row) => row.assertions.includes("backend-denial")).map((row) => ({ id: row.id, assertion: "backend-denial" }));
    const actual = [...FAULT_ASSERTION_OWNERS["fault-denial"]];
    expect(actual.sort((left, right) => left.id.localeCompare(right.id))).toEqual(declared.sort((left, right) => left.id.localeCompare(right.id)));
    expect(actual).toHaveLength(7);
  });

  it.each([
    ["portable-api:runPortableTransfer", ["contract", "resume", "replay"]],
    ["portable-api:openSqlitePortableDestination", ["contract", "mismatch-refusal"]],
    ["portable-api:createPostgreSqlPortableDestination", ["contract", "mismatch-refusal"]],
  ] as const)("requires the declared recovery assertions for %s", (id, assertions) => {
    expect(matrix.find((row) => row.id === id)!.assertions).toEqual(assertions);
    for (const omitted of assertions.slice(1)) {
      const incomplete = structuredClone(matrix);
      const row = incomplete.find((entry) => entry.id === id)!;
      row.assertions = row.assertions.filter((assertion) => assertion !== omitted);
      expect(() => assertMatrixMatches(discovered, incomplete)).toThrow();
    }
  });

  it("requires alias-dispatch evidence whenever actual registration declares an alias", () => {
    const changed = structuredClone(discovered);
    changed.find((row) => row.id === "cli:search")!.registration.aliases = ["lookup"];
    const updated = JSON.parse(renderMatrix(changed)) as SurfaceRow[];
    expect(updated.find((row) => row.id === "cli:search")!.assertions).toEqual([...scenarioMap["cli:search"].assertions, "alias-dispatch"]);
    expect(() => assertMatrixMatches(changed, matrix)).toThrow();
  });

  it("records root custom help flags and topics outside Commander", () => {
    const cli = readFileSync(new URL("../../../bin/lcm.ts", import.meta.url), "utf8");
    const help = readFileSync(new URL("../../../src/cli-help.ts", import.meta.url), "utf8");
    const grammar = extractCustomHelpGrammar(cli, help);
    expect(grammar.flags).toEqual(["--", "--help", "-h"]);
    expect(grammar.topics).toContain("search");
    expect(discovered.find((row) => row.id === "cli:<root>")!.registration.customHelp).toEqual(grammar);
    expect(() => extractCustomHelpGrammar(cli.replace("function resolveCustomHelpRequest", "function renamedHelp"), help)).toThrow();
    expect(() => extractCustomHelpGrammar(cli, help.replace("const HELP:", "const RENAMED:"))).toThrow();
  });

  it.each([0, 7])("the explicit launcher isolates update mode and propagates exit %i", (exitCode) => {
    const root = mkdtempSync(join(tmpdir(), "lcm-inventory-launcher-"));
    const original = process.env.LCM_SURFACE_MATRIX_UPDATE;
    try {
      mkdirSync(join(root, "scripts"));
      mkdirSync(join(root, "node_modules", "vitest"), { recursive: true });
      copyFileSync(new URL("../../../scripts/generate-surface-parity-inventory.mjs", import.meta.url), join(root, "scripts", "generate-surface-parity-inventory.mjs"));
      writeFileSync(join(root, "node_modules", "vitest", "package.json"), JSON.stringify({ name: "vitest", type: "module" }));
      writeFileSync(join(root, "node_modules", "vitest", "vitest.mjs"), `import { writeFileSync } from "node:fs"; writeFileSync("observed.json", JSON.stringify({args:process.argv.slice(2),update:process.env.LCM_SURFACE_MATRIX_UPDATE})); process.exitCode = ${exitCode};`);
      const result = spawnSync(process.execPath, [join(root, "scripts", "generate-surface-parity-inventory.mjs")], { env: { ...process.env, LCM_SURFACE_MATRIX_UPDATE: "parent-value" }, encoding: "utf8", timeout: 10_000 });
      expect(result.error).toBeUndefined();
      expect(result.status).toBe(exitCode);
      expect(JSON.parse(readFileSync(join(root, "observed.json"), "utf8"))).toEqual({ args: ["run", "test/daemon/routes/surface-parity-inventory.test.ts"], update: "1" });
      expect(process.env.LCM_SURFACE_MATRIX_UPDATE).toBe(original);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

});
