export const LCM_MARKERS = {
  START: '<!-- lcm -->',
  END: '<!-- lcm -->',
} as const;

/** Exact standalone marker used to opt a skill path into LCM ownership. */
export const LCM_MANAGED_SKILL_MARKER = '<!-- lcm-managed-skill:v1 -->';

/**
 * SHA-256 digests of unmarked skills generated by released LCM revisions.
 * Keep this list compact and exact: it is a migration allowlist, not a
 * content signature for arbitrary Markdown.
 */
export const LCM_HISTORICAL_SKILL_SHA256 = [
  '497b6c2bf90b4bf52b6ef43cb8b9f634de49cf3741a8c495db641eb7f380d14c',
  '6a382e36de44d8e9fbb72362300c263eb24259d3bc0675031b31b272d95458ba',
  '6af2b5b4666867071e2afcdf5610b39b02915bbea4937e9ebb4597229e48b473',
  'c4a4172b54ae2d562ee98f530315071c1ccdf85867ebf429f6d155805d284fcc',
  '78596dc5d5398993a4a8f63829931e0f3e3914b4d467925f1ade3089fb0802a8',
  '9a67d0a5450daa4b9aabec6c6eb16c7e5e07da6ed89de6ac3d962c1a95e8dddd',
  '6c1757c7434102bb62e6faac25796f7bd1d7c26ff2479c53a9f7497b36076c57',
] as const;
