DO $migration$
BEGIN
  IF current_setting('server_version_num')::integer / 10000 <> 18 THEN
    RAISE EXCEPTION 'LCM PostgreSQL schema requires PostgreSQL major version 18'
      USING ERRCODE = 'feature_not_supported';
  END IF;
END
$migration$;

DO $migration$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_namespace AS namespace
    CROSS JOIN LATERAL pg_catalog.aclexplode(
      COALESCE(namespace.nspacl, pg_catalog.acldefault('n', namespace.nspowner))
    ) AS privilege
    WHERE namespace.nspname = 'lcm'
      AND privilege.grantee = 0
      AND privilege.privilege_type = 'CREATE'
  ) THEN
    RAISE EXCEPTION 'LCM PostgreSQL schema refuses PUBLIC CREATE privilege on schema lcm'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
END
$migration$;

CREATE FUNCTION lcm.normalize_search_text(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = pg_catalog, public
RETURN public.unaccent('public.unaccent'::regdictionary, pg_catalog.lower(COALESCE(input, '')));

CREATE TABLE lcm.machines (
  machine_id uuid PRIMARY KEY DEFAULT uuidv7(),
  identity_key text NOT NULL UNIQUE CHECK (btrim(identity_key) <> ''),
  display_name text CHECK (display_name IS NULL OR btrim(display_name) <> ''),
  registered_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  last_seen_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  CHECK ((uuid_extract_version(machine_id) = 7) IS TRUE),
  CHECK (last_seen_at >= registered_at)
);

CREATE TABLE lcm.projects (
  project_id uuid PRIMARY KEY DEFAULT uuidv7(),
  display_name text NOT NULL CHECK (btrim(display_name) <> ''),
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  CHECK ((uuid_extract_version(project_id) = 7) IS TRUE),
  CHECK (updated_at >= created_at)
);

CREATE TABLE lcm.project_aliases (
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  machine_id uuid NOT NULL REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  path text NOT NULL CHECK (path <> ''),
  normalized_path text NOT NULL CHECK (normalized_path <> '' AND normalized_path = btrim(normalized_path)),
  linked_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (machine_id, normalized_path)
);

CREATE INDEX project_aliases_project_idx
  ON lcm.project_aliases (project_id, machine_id, normalized_path);

CREATE TABLE lcm.conversations (
  conversation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  session_id text NOT NULL CHECK (btrim(session_id) <> ''),
  title text,
  bootstrapped_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  UNIQUE (project_id, session_id),
  UNIQUE (project_id, conversation_id),
  CHECK (updated_at >= created_at),
  CHECK (bootstrapped_at IS NULL OR bootstrapped_at >= created_at)
);

CREATE INDEX conversations_project_order_idx
  ON lcm.conversations (project_id, created_at DESC, conversation_id DESC);

CREATE TABLE lcm.messages (
  message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  seq bigint NOT NULL CHECK (seq >= 0),
  role text NOT NULL CHECK (role IN ('system', 'user', 'assistant', 'tool')),
  content text NOT NULL,
  token_count bigint NOT NULL CHECK (token_count >= 0),
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  search_document tsvector GENERATED ALWAYS AS (
    to_tsvector('pg_catalog.simple'::regconfig, lcm.normalize_search_text(content))
  ) STORED,
  UNIQUE (project_id, conversation_id, seq),
  UNIQUE (project_id, conversation_id, message_id),
  FOREIGN KEY (project_id, conversation_id)
    REFERENCES lcm.conversations(project_id, conversation_id) ON DELETE CASCADE
);

CREATE INDEX messages_project_created_idx
  ON lcm.messages (project_id, created_at DESC, message_id DESC);
CREATE INDEX messages_search_document_idx
  ON lcm.messages USING gin (search_document);
CREATE INDEX messages_content_trgm_idx
  ON lcm.messages USING gin (lcm.normalize_search_text(content) public.gin_trgm_ops);

CREATE TABLE lcm.message_parts (
  part_id uuid PRIMARY KEY DEFAULT uuidv7(),
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  message_id bigint NOT NULL,
  session_id text NOT NULL CHECK (btrim(session_id) <> ''),
  part_type text NOT NULL CHECK (part_type IN (
    'text', 'reasoning', 'tool', 'patch', 'file', 'subtask', 'compaction',
    'step_start', 'step_finish', 'snapshot', 'agent', 'retry'
  )),
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  text_content text,
  is_ignored boolean,
  is_synthetic boolean,
  tool_call_id text,
  tool_name text,
  tool_status text,
  tool_input text,
  tool_output text,
  tool_error text,
  tool_title text,
  patch_hash text,
  patch_files text,
  file_mime text,
  file_name text,
  file_url text,
  subtask_prompt text,
  subtask_desc text,
  subtask_agent text,
  step_reason text,
  step_cost double precision CHECK (step_cost IS NULL OR step_cost >= 0),
  step_tokens_in bigint CHECK (step_tokens_in IS NULL OR step_tokens_in >= 0),
  step_tokens_out bigint CHECK (step_tokens_out IS NULL OR step_tokens_out >= 0),
  snapshot_hash text,
  compaction_auto boolean,
  metadata jsonb CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object'),
  UNIQUE (project_id, conversation_id, message_id, ordinal),
  FOREIGN KEY (project_id, conversation_id, message_id)
    REFERENCES lcm.messages(project_id, conversation_id, message_id) ON DELETE CASCADE
);

CREATE INDEX message_parts_type_idx
  ON lcm.message_parts (project_id, part_type, message_id, ordinal);
CREATE INDEX message_parts_metadata_idx
  ON lcm.message_parts USING gin (metadata jsonb_path_ops) WHERE metadata IS NOT NULL;

CREATE TABLE lcm.native_transcripts (
  transcript_id uuid PRIMARY KEY DEFAULT uuidv7(),
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  machine_id uuid NOT NULL REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  client_name text NOT NULL CHECK (btrim(client_name) <> ''),
  format_name text NOT NULL CHECK (btrim(format_name) <> ''),
  format_version text NOT NULL CHECK (btrim(format_version) <> ''),
  native_session_id text NOT NULL CHECK (btrim(native_session_id) <> ''),
  source_locator text NOT NULL CHECK (source_locator <> ''),
  source_ordinal bigint NOT NULL CHECK (source_ordinal >= 0),
  observed_at timestamptz NOT NULL,
  ingested_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  scrubber_version text NOT NULL CHECK (btrim(scrubber_version) <> ''),
  content_sha256 text NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  ingest_key text NOT NULL CHECK (ingest_key ~ '^[0-9a-f]{64}$'),
  native_payload jsonb NOT NULL CHECK (jsonb_typeof(native_payload) IN ('object', 'array')),
  UNIQUE (project_id, machine_id, ingest_key),
  UNIQUE (project_id, transcript_id),
  CHECK ((uuid_extract_version(transcript_id) = 7) IS TRUE),
  CHECK (ingested_at >= observed_at)
);

CREATE INDEX native_transcripts_source_order_idx
  ON lcm.native_transcripts (
    project_id, machine_id, client_name, source_locator, source_ordinal, transcript_id
  );
CREATE INDEX native_transcripts_session_idx
  ON lcm.native_transcripts (project_id, native_session_id, observed_at, transcript_id);
CREATE INDEX native_transcripts_machine_idx
  ON lcm.native_transcripts (machine_id, transcript_id);
CREATE INDEX native_transcripts_payload_idx
  ON lcm.native_transcripts USING gin (native_payload jsonb_path_ops);

CREATE TABLE lcm.transcript_messages (
  project_id uuid NOT NULL,
  transcript_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  message_id bigint NOT NULL,
  source_ordinal integer NOT NULL CHECK (source_ordinal >= 0),
  PRIMARY KEY (project_id, transcript_id, message_id),
  UNIQUE (project_id, transcript_id, source_ordinal),
  FOREIGN KEY (project_id, transcript_id)
    REFERENCES lcm.native_transcripts(project_id, transcript_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, conversation_id, message_id)
    REFERENCES lcm.messages(project_id, conversation_id, message_id) ON DELETE RESTRICT
);

CREATE INDEX transcript_messages_message_idx
  ON lcm.transcript_messages (project_id, conversation_id, message_id, transcript_id);

CREATE TABLE lcm.summaries (
  summary_id uuid PRIMARY KEY DEFAULT uuidv7(),
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  kind text NOT NULL CHECK (kind IN ('leaf', 'condensed')),
  depth integer NOT NULL DEFAULT 0 CHECK (depth >= 0),
  content text NOT NULL,
  token_count bigint NOT NULL CHECK (token_count >= 0),
  earliest_at timestamptz,
  latest_at timestamptz,
  descendant_count bigint NOT NULL DEFAULT 0 CHECK (descendant_count >= 0),
  descendant_token_count bigint NOT NULL DEFAULT 0 CHECK (descendant_token_count >= 0),
  source_message_token_count bigint NOT NULL DEFAULT 0 CHECK (source_message_token_count >= 0),
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  search_document tsvector GENERATED ALWAYS AS (
    to_tsvector('pg_catalog.simple'::regconfig, lcm.normalize_search_text(content))
  ) STORED,
  UNIQUE (project_id, summary_id),
  UNIQUE (project_id, conversation_id, summary_id),
  FOREIGN KEY (project_id, conversation_id)
    REFERENCES lcm.conversations(project_id, conversation_id) ON DELETE CASCADE,
  CHECK ((earliest_at IS NULL) = (latest_at IS NULL)),
  CHECK (earliest_at IS NULL OR earliest_at <= latest_at)
);

CREATE INDEX summaries_conversation_order_idx
  ON lcm.summaries (project_id, conversation_id, created_at, summary_id);
CREATE INDEX summaries_project_recent_idx
  ON lcm.summaries (project_id, created_at DESC, summary_id DESC);
CREATE INDEX summaries_search_document_idx
  ON lcm.summaries USING gin (search_document);
CREATE INDEX summaries_content_trgm_idx
  ON lcm.summaries USING gin (lcm.normalize_search_text(content) public.gin_trgm_ops);

CREATE TABLE lcm.summary_messages (
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  summary_id uuid NOT NULL,
  message_id bigint NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  PRIMARY KEY (project_id, summary_id, message_id),
  UNIQUE (project_id, summary_id, ordinal),
  FOREIGN KEY (project_id, conversation_id, summary_id)
    REFERENCES lcm.summaries(project_id, conversation_id, summary_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, conversation_id, message_id)
    REFERENCES lcm.messages(project_id, conversation_id, message_id) ON DELETE RESTRICT
);

CREATE INDEX summary_messages_message_idx
  ON lcm.summary_messages (project_id, conversation_id, message_id, summary_id);
CREATE INDEX summary_messages_summary_idx
  ON lcm.summary_messages (project_id, conversation_id, summary_id);

CREATE TABLE lcm.summary_parents (
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  summary_id uuid NOT NULL,
  parent_summary_id uuid NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  PRIMARY KEY (project_id, summary_id, parent_summary_id),
  UNIQUE (project_id, summary_id, ordinal),
  FOREIGN KEY (project_id, conversation_id, summary_id)
    REFERENCES lcm.summaries(project_id, conversation_id, summary_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, conversation_id, parent_summary_id)
    REFERENCES lcm.summaries(project_id, conversation_id, summary_id) ON DELETE RESTRICT,
  CHECK (summary_id <> parent_summary_id)
);

CREATE INDEX summary_parents_parent_idx
  ON lcm.summary_parents (project_id, conversation_id, parent_summary_id, ordinal, summary_id);
CREATE INDEX summary_parents_summary_idx
  ON lcm.summary_parents (project_id, conversation_id, summary_id);

CREATE TABLE lcm.context_items (
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  item_type text NOT NULL CHECK (item_type IN ('message', 'summary')),
  message_id bigint,
  summary_id uuid,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (project_id, conversation_id, ordinal),
  FOREIGN KEY (project_id, conversation_id)
    REFERENCES lcm.conversations(project_id, conversation_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, conversation_id, message_id)
    REFERENCES lcm.messages(project_id, conversation_id, message_id) ON DELETE RESTRICT,
  FOREIGN KEY (project_id, conversation_id, summary_id)
    REFERENCES lcm.summaries(project_id, conversation_id, summary_id) ON DELETE RESTRICT,
  CHECK (
    (item_type = 'message' AND message_id IS NOT NULL AND summary_id IS NULL) OR
    (item_type = 'summary' AND summary_id IS NOT NULL AND message_id IS NULL)
  )
);

CREATE INDEX context_items_message_idx
  ON lcm.context_items (project_id, conversation_id, message_id) WHERE message_id IS NOT NULL;
CREATE INDEX context_items_summary_idx
  ON lcm.context_items (project_id, conversation_id, summary_id) WHERE summary_id IS NOT NULL;

CREATE TABLE lcm.large_files (
  file_id uuid PRIMARY KEY DEFAULT uuidv7(),
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  file_name text,
  mime_type text,
  byte_size bigint CHECK (byte_size IS NULL OR byte_size >= 0),
  storage_uri text NOT NULL CHECK (btrim(storage_uri) <> ''),
  exploration_summary text,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  UNIQUE (project_id, conversation_id, file_id),
  FOREIGN KEY (project_id, conversation_id)
    REFERENCES lcm.conversations(project_id, conversation_id) ON DELETE CASCADE
);

CREATE INDEX large_files_conversation_order_idx
  ON lcm.large_files (project_id, conversation_id, created_at, file_id);

CREATE TABLE lcm.summary_large_files (
  project_id uuid NOT NULL,
  conversation_id bigint NOT NULL,
  summary_id uuid NOT NULL,
  file_id uuid NOT NULL,
  ordinal integer NOT NULL CHECK (ordinal >= 0),
  PRIMARY KEY (project_id, summary_id, file_id),
  UNIQUE (project_id, summary_id, ordinal),
  FOREIGN KEY (project_id, conversation_id, summary_id)
    REFERENCES lcm.summaries(project_id, conversation_id, summary_id) ON DELETE CASCADE,
  FOREIGN KEY (project_id, conversation_id, file_id)
    REFERENCES lcm.large_files(project_id, conversation_id, file_id) ON DELETE RESTRICT
);

CREATE INDEX summary_large_files_file_idx
  ON lcm.summary_large_files (project_id, conversation_id, file_id, summary_id);
CREATE INDEX summary_large_files_summary_idx
  ON lcm.summary_large_files (project_id, conversation_id, summary_id);

CREATE TABLE lcm.promoted_memories (
  memory_id uuid PRIMARY KEY DEFAULT uuidv7(),
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  content text NOT NULL CHECK (content <> ''),
  source_summary_id uuid,
  session_id text,
  depth integer NOT NULL DEFAULT 0 CHECK (depth >= 0),
  confidence double precision NOT NULL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  archived_at timestamptz,
  search_document tsvector GENERATED ALWAYS AS (
    to_tsvector('pg_catalog.simple'::regconfig, lcm.normalize_search_text(content))
  ) STORED,
  UNIQUE (project_id, memory_id),
  FOREIGN KEY (project_id, source_summary_id)
    REFERENCES lcm.summaries(project_id, summary_id) ON DELETE SET NULL (source_summary_id),
  CHECK (archived_at IS NULL OR archived_at >= created_at)
);

CREATE INDEX promoted_memories_active_order_idx
  ON lcm.promoted_memories (project_id, created_at, memory_id) WHERE archived_at IS NULL;
CREATE INDEX promoted_memories_source_summary_idx
  ON lcm.promoted_memories (project_id, source_summary_id);
CREATE INDEX promoted_memories_metadata_idx
  ON lcm.promoted_memories USING gin (metadata jsonb_path_ops);
CREATE INDEX promoted_memories_search_document_idx
  ON lcm.promoted_memories USING gin (search_document);
CREATE INDEX promoted_memories_content_trgm_idx
  ON lcm.promoted_memories USING gin (lcm.normalize_search_text(content) public.gin_trgm_ops);

CREATE TABLE lcm.promoted_memory_tags (
  project_id uuid NOT NULL,
  memory_id uuid NOT NULL,
  tag text NOT NULL CHECK (tag <> '' AND tag = btrim(tag)),
  normalized_tag text GENERATED ALWAYS AS (lower(tag)) STORED,
  PRIMARY KEY (project_id, memory_id, normalized_tag),
  FOREIGN KEY (project_id, memory_id)
    REFERENCES lcm.promoted_memories(project_id, memory_id) ON DELETE CASCADE
);

CREATE INDEX promoted_memory_tags_lookup_idx
  ON lcm.promoted_memory_tags (project_id, normalized_tag, memory_id);

CREATE TABLE lcm.recall_surfacing (
  surfacing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL,
  memory_id uuid NOT NULL,
  session_id text,
  surfaced_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  FOREIGN KEY (project_id, memory_id)
    REFERENCES lcm.promoted_memories(project_id, memory_id) ON DELETE CASCADE
);

CREATE INDEX recall_surfacing_memory_order_idx
  ON lcm.recall_surfacing (project_id, memory_id, surfaced_at DESC, surfacing_id DESC);
CREATE INDEX recall_surfacing_session_order_idx
  ON lcm.recall_surfacing (project_id, session_id, surfaced_at, surfacing_id)
  WHERE session_id IS NOT NULL;

CREATE TABLE lcm.redaction_counters (
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  category text NOT NULL CHECK (category IN ('built_in', 'global', 'project', 'gitleaks')),
  count bigint NOT NULL DEFAULT 0 CHECK (count >= 0),
  updated_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (project_id, category)
);

CREATE TABLE lcm.ingest_checkpoints (
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  machine_id uuid NOT NULL REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  client_name text NOT NULL CHECK (btrim(client_name) <> ''),
  source_locator text NOT NULL CHECK (source_locator <> ''),
  last_source_ordinal bigint NOT NULL DEFAULT 0 CHECK (last_source_ordinal >= 0),
  imported_count bigint NOT NULL DEFAULT 0 CHECK (imported_count >= 0),
  skipped_count bigint NOT NULL DEFAULT 0 CHECK (skipped_count >= 0),
  quarantined_count bigint NOT NULL DEFAULT 0 CHECK (quarantined_count >= 0),
  checkpoint jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(checkpoint) = 'object'),
  updated_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (project_id, machine_id, client_name, source_locator)
);

CREATE INDEX ingest_checkpoints_payload_idx
  ON lcm.ingest_checkpoints USING gin (checkpoint jsonb_path_ops);
CREATE INDEX ingest_checkpoints_machine_idx
  ON lcm.ingest_checkpoints (machine_id, project_id, client_name, source_locator);

CREATE TABLE lcm.session_ingest_log (
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  session_id text NOT NULL CHECK (btrim(session_id) <> ''),
  message_count bigint NOT NULL DEFAULT 0 CHECK (message_count >= 0),
  completed_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  PRIMARY KEY (project_id, session_id)
);

CREATE INDEX session_ingest_log_completed_idx
  ON lcm.session_ingest_log (project_id, completed_at DESC, session_id);

CREATE TABLE lcm.session_instructions (
  instruction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  machine_id uuid REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  slot integer NOT NULL DEFAULT 1 CHECK (slot >= 0),
  content text NOT NULL,
  content_hash text NOT NULL CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  updated_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  UNIQUE NULLS NOT DISTINCT (project_id, machine_id, slot)
);

CREATE INDEX session_instructions_machine_idx
  ON lcm.session_instructions (machine_id, instruction_id) WHERE machine_id IS NOT NULL;

CREATE TABLE lcm.passive_event_inbox (
  inbox_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  machine_id uuid NOT NULL REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  event_id uuid NOT NULL,
  event_version integer NOT NULL CHECK (event_version > 0),
  machine_sequence bigint NOT NULL CHECK (machine_sequence >= 0),
  event_type text NOT NULL CHECK (btrim(event_type) <> ''),
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'claimed', 'retry', 'applied', 'quarantined'
  )),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  received_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  next_attempt_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  claimed_at timestamptz,
  claimed_by text,
  applied_at timestamptz,
  quarantined_at timestamptz,
  quarantine_reason text,
  UNIQUE (machine_id, event_id),
  UNIQUE (machine_id, machine_sequence),
  CHECK ((claimed_at IS NULL) = (claimed_by IS NULL)),
  CHECK ((status = 'claimed') = (claimed_at IS NOT NULL)),
  CHECK ((status = 'applied') = (applied_at IS NOT NULL)),
  CHECK ((status = 'quarantined') = (quarantined_at IS NOT NULL)),
  CHECK ((quarantined_at IS NULL) = (quarantine_reason IS NULL)),
  CHECK (claimed_at IS NULL OR claimed_at >= received_at),
  CHECK (applied_at IS NULL OR applied_at >= received_at),
  CHECK (quarantined_at IS NULL OR quarantined_at >= received_at)
);

CREATE INDEX passive_event_inbox_ready_idx
  ON lcm.passive_event_inbox (project_id, machine_id, machine_sequence, inbox_id)
  WHERE status IN ('pending', 'retry');
CREATE INDEX passive_event_inbox_retry_idx
  ON lcm.passive_event_inbox (next_attempt_at, project_id, machine_id, machine_sequence)
  WHERE status = 'retry';
CREATE INDEX passive_event_inbox_claimed_idx
  ON lcm.passive_event_inbox (claimed_at, project_id, machine_id, machine_sequence)
  WHERE status = 'claimed';
CREATE INDEX passive_event_inbox_payload_idx
  ON lcm.passive_event_inbox USING gin (payload jsonb_path_ops);
CREATE INDEX passive_event_inbox_project_idx
  ON lcm.passive_event_inbox (project_id, inbox_id);

CREATE TABLE lcm.fenced_leases (
  project_id uuid NOT NULL REFERENCES lcm.projects(project_id) ON DELETE RESTRICT,
  resource_type text NOT NULL CHECK (btrim(resource_type) <> ''),
  resource_key text NOT NULL CHECK (btrim(resource_key) <> ''),
  owner_machine_id uuid NOT NULL REFERENCES lcm.machines(machine_id) ON DELETE RESTRICT,
  owner_process_id text NOT NULL CHECK (btrim(owner_process_id) <> ''),
  operation text NOT NULL CHECK (btrim(operation) <> ''),
  fencing_token bigint NOT NULL CHECK (fencing_token > 0),
  acquired_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  renewed_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  expires_at timestamptz NOT NULL,
  released_at timestamptz,
  PRIMARY KEY (project_id, resource_type, resource_key),
  CHECK (renewed_at >= acquired_at),
  CHECK (expires_at > renewed_at),
  CHECK (released_at IS NULL OR released_at >= renewed_at)
);

CREATE INDEX fenced_leases_owner_idx
  ON lcm.fenced_leases (owner_machine_id, owner_process_id, operation)
  WHERE released_at IS NULL;
CREATE INDEX fenced_leases_expiry_idx
  ON lcm.fenced_leases (expires_at, project_id, resource_type, resource_key)
  WHERE released_at IS NULL;
CREATE INDEX fenced_leases_owner_machine_idx
  ON lcm.fenced_leases (owner_machine_id, project_id, resource_type, resource_key);

REVOKE ALL PRIVILEGES ON TABLE
  lcm.schema_migrations,
  lcm.machines,
  lcm.projects,
  lcm.project_aliases,
  lcm.conversations,
  lcm.messages,
  lcm.message_parts,
  lcm.native_transcripts,
  lcm.transcript_messages,
  lcm.summaries,
  lcm.summary_messages,
  lcm.summary_parents,
  lcm.context_items,
  lcm.large_files,
  lcm.summary_large_files,
  lcm.promoted_memories,
  lcm.promoted_memory_tags,
  lcm.recall_surfacing,
  lcm.redaction_counters,
  lcm.ingest_checkpoints,
  lcm.session_ingest_log,
  lcm.session_instructions,
  lcm.passive_event_inbox,
  lcm.fenced_leases
FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SEQUENCE
  lcm.conversations_conversation_id_seq,
  lcm.messages_message_id_seq,
  lcm.recall_surfacing_surfacing_id_seq,
  lcm.session_instructions_instruction_id_seq,
  lcm.passive_event_inbox_inbox_id_seq
FROM PUBLIC;
REVOKE ALL PRIVILEGES ON FUNCTION lcm.normalize_search_text(text) FROM PUBLIC;
