import { createHash, randomBytes, randomUUID } from "node:crypto";
import { closeSync, constants, existsSync, fchmodSync, fstatSync, fsyncSync, lstatSync, mkdirSync, openSync, readSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import { lcmHomeDir } from "../runtime-paths.js";
import { ensurePrivateDirectory, PRIVATE_DIRECTORY_MODE, PRIVATE_FILE_MODE } from "../security-files.js";

export const MIGRATION_MANIFEST_VERSION = 1 as const;
export const MIGRATION_ARTIFACT_MAX_BYTES = 8 * 1024 * 1024;
export const MIGRATION_DEFAULT_BATCH_SIZE = 500;
export const MIGRATION_DEFAULT_SAMPLE_SIZE = 25;
const SHA256 = /^[a-f0-9]{64}$/u;
const GENERATION = /^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u;

export type MigrationBackend = "sqlite" | "postgresql";
export type MigrationDirection = "sqlite-to-postgresql" | "postgresql-to-sqlite";
export type MigrationStatus = "planned" | "dry-run-verified" | "applying" | "applied" | "verified" | "active" | "rollback-ready" | "rolled-back" | "failed";
export type PublicationOperation = "activate" | "pre-write-rollback" | "post-write-rollback";
export type PublicationPhase = "prepare" | "commit" | "recovery" | "completed";
export interface CanonicalInteger { readonly $integer: string }
export type CanonicalScalar = boolean | CanonicalInteger | null | number | string;
export type CanonicalValue = CanonicalScalar | CanonicalValue[] | { readonly [key: string]: CanonicalValue };

export interface MigrationFileFingerprint { readonly path: string; readonly device: number; readonly inode: number; readonly size: number; readonly mtimeMs: number; readonly sha256: string }
export interface MigrationSourceFingerprint { readonly main: MigrationFileFingerprint; readonly wal: MigrationFileFingerprint | null; readonly schemaSha256: string }
export interface MigrationSnapshotIdentity { readonly relativePath: string; readonly file: MigrationFileFingerprint; readonly schemaSha256: string; readonly logicalRows: number; readonly logicalSha256: string; readonly createdAt: string }
export type MigrationInventoryArtifactKind = "event-sidecar" | "project-database" | "project-map";
export interface MigrationInventoryArtifact { readonly kind: MigrationInventoryArtifactKind; readonly relativePath: string; readonly localProjectId: string | null; readonly identitySha256: string }
export interface MigrationProjectIdentity { readonly localProjectId: string; readonly canonicalPath: string; readonly aliases: readonly string[]; readonly remoteProjectId: string }
export interface MigrationTableCheckpoint { readonly table: string; readonly copiedRows: number; readonly sourceRows: number; readonly sourceSha256: string; readonly destinationRows?: number; readonly destinationSha256?: string; readonly lastKey?: readonly CanonicalScalar[]; readonly lastBatchSha256?: string; readonly remoteFencingToken?: string; readonly remoteOutcome?: "committed" | "readback-verified"; readonly verifiedAt?: string }
export interface MigrationDeliveryGate { readonly blockingOutbox: number; readonly quarantined: number; readonly checkedAt: string }
export interface MigrationQuiescence { readonly daemonStopped: true; readonly verifiedAt: string; readonly sourceMainSha256: string; readonly sourceWalSha256: string | null }
export interface MigrationOperationalEvidence { readonly payloadMinimized: true; readonly originalMainArchive: MigrationFileFingerprint | null; readonly originalWalArchive: MigrationFileFingerprint | null; readonly nativeTranscriptSidecar: MigrationFileFingerprint | null; readonly passiveEventSidecar: MigrationFileFingerprint | null; readonly checkpointSidecar: MigrationFileFingerprint | null }
export interface MigrationProjectState { readonly identity: MigrationProjectIdentity; readonly status: MigrationStatus; readonly sourceFingerprint: MigrationSourceFingerprint | null; readonly snapshot: MigrationSnapshotIdentity | null; readonly quiescence: MigrationQuiescence | null; readonly tables: readonly MigrationTableCheckpoint[]; readonly delivery: MigrationDeliveryGate | null; readonly operationalEvidence: MigrationOperationalEvidence; readonly appliedAt?: string; readonly verifiedAt?: string; readonly activatedAt?: string; readonly failure?: string }
export interface MigrationInstallationCoverage { readonly inventorySha256: string; readonly projectMapSha256: string; readonly inventory: readonly MigrationInventoryArtifact[]; readonly activeLocalProjectIds: readonly string[]; readonly representedLocalProjectIds: readonly string[]; readonly orphanArtifacts: readonly string[]; readonly complete: boolean; readonly checkedAt: string }
export interface MigrationProtocolContract { readonly stableResume: "immutable-snapshot-offset-v1"; readonly integerEncoding: "decimal-tagged-v1"; readonly idempotentWrites: "exact-readback-v1"; readonly deterministicSampling: "sha256-key-v1"; readonly uncertainCommit: "authoritative-remote-readback-v1"; readonly activationReadiness: "factory-health-existing-projects-v1" }
export interface MigrationManifest { readonly version: typeof MIGRATION_MANIFEST_VERSION; readonly generationId: string; readonly direction: MigrationDirection; readonly status: MigrationStatus; readonly createdAt: string; readonly updatedAt: string; readonly batchSize: number; readonly sampleSize: number; readonly coverage: MigrationInstallationCoverage; readonly sourceBackend: MigrationBackend; readonly destinationBackend: MigrationBackend; readonly schemaManifestSha256: string; readonly protocol: MigrationProtocolContract; readonly projects: readonly MigrationProjectState[]; readonly dryRunVerifiedAt?: string; readonly appliedAt?: string; readonly verifiedAt?: string; readonly activatedAt?: string; readonly failure?: string }
export interface MigrationCheckpoint { readonly version: typeof MIGRATION_MANIFEST_VERSION; readonly generationId: string; readonly manifestSha256: string; readonly updatedAt: string; readonly projects: readonly { readonly localProjectId: string; readonly status: MigrationStatus; readonly tables: readonly MigrationTableCheckpoint[] }[] }
export interface MigrationVerificationReport { readonly version: typeof MIGRATION_MANIFEST_VERSION; readonly generationId: string; readonly generatedAt: string; readonly status: MigrationStatus; readonly ready: boolean; readonly blockers: readonly string[]; readonly projects: readonly { readonly localProjectId: string; readonly remoteProjectId: string; readonly verified: boolean; readonly tables: readonly MigrationTableCheckpoint[] }[] }
export interface PublicationProjectState { readonly generationId: string; readonly localProjectId: string; readonly remoteProjectId: string; readonly sourceFingerprintSha256: string; readonly manifestSha256: string; readonly expectedCanonicalPath: string; readonly expectedAliasesSha256: string; readonly stagedSqlitePath?: string; readonly archivedMainPath?: string; readonly archivedWalPath?: string; readonly published: boolean }
export interface MigrationPublicationJournal { readonly version: typeof MIGRATION_MANIFEST_VERSION; readonly generationId: string; readonly operation: PublicationOperation; readonly phase: PublicationPhase; readonly createdAt: string; readonly updatedAt: string; readonly expectedBackend: MigrationBackend; readonly targetBackend: MigrationBackend; readonly expectedConfigSha256: string; readonly publishedConfigSha256?: string; readonly projects: readonly PublicationProjectState[] }
export interface MigrationGenerationPaths { readonly root: string; readonly directory: string; readonly projectsDirectory: string; readonly manifest: string; readonly checkpoint: string; readonly report: string; readonly journal: string }
export interface MigrationProjectPaths { readonly directory: string; readonly sourceSnapshot: string; readonly reverseDatabase: string; readonly originalMainArchive: string; readonly originalWalArchive: string; readonly nativeTranscriptSidecar: string; readonly passiveEventSidecar: string; readonly checkpointSidecar: string }

function record(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function timestamp(value: unknown): value is string { return typeof value === "string" && Number.isFinite(Date.parse(value)); }
function canonicalize(value: unknown, seen: Set<object>): CanonicalValue {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") { if (!Number.isFinite(value)) throw new TypeError("canonical JSON rejects non-finite numbers"); return Object.is(value, -0) ? 0 : value; }
  if (typeof value === "bigint") return { $integer: value.toString() };
  if (value instanceof Date) { if (!Number.isFinite(value.getTime())) throw new TypeError("canonical JSON rejects invalid dates"); return value.toISOString(); }
  if (Array.isArray(value)) { if (seen.has(value)) throw new TypeError("canonical JSON rejects cycles"); seen.add(value); try { return value.map((entry) => canonicalize(entry, seen)); } finally { seen.delete(value); } }
  if (record(value)) { if (seen.has(value)) throw new TypeError("canonical JSON rejects cycles"); seen.add(value); try { return Object.fromEntries(Object.keys(value).sort().map((key) => { const entry = value[key]; if (entry === undefined || typeof entry === "function" || typeof entry === "symbol") throw new TypeError(`canonical JSON rejects unsupported value at ${key}`); return [key, canonicalize(entry, seen)]; })); } finally { seen.delete(value); } }
  throw new TypeError(`canonical JSON rejects ${typeof value}`);
}
export function canonicalJson(value: unknown): string { return JSON.stringify(canonicalize(value, new Set())); }
export function sha256Text(value: string): string { return createHash("sha256").update(value, "utf8").digest("hex"); }
export function sha256Canonical(value: unknown): string { return sha256Text(canonicalJson(value)); }
export class CanonicalRowDigest { private readonly hash = createHash("sha256"); private rows = 0; private completed = false; update(row: unknown): void { if (this.completed) throw new Error("canonical row digest is already complete"); const value = canonicalJson(row); this.hash.update(String(Buffer.byteLength(value)), "ascii").update(":", "ascii").update(value, "utf8"); this.rows += 1; } digest(): { readonly rows: number; readonly sha256: string } { if (this.completed) throw new Error("canonical row digest is already complete"); this.completed = true; return { rows: this.rows, sha256: this.hash.digest("hex") }; } }

function contained(root: string, candidate: string): boolean { const base = resolve(root); const path = resolve(candidate); return path === base || path.startsWith(`${base}${sep}`); }
export function migrationsRoot(homeDir?: string): string { return join(lcmHomeDir(homeDir), "migrations"); }
export function migrationGenerationPaths(generationId: string, homeDir?: string): MigrationGenerationPaths { if (!GENERATION.test(generationId)) throw new Error("invalid migration generation id"); const root = migrationsRoot(homeDir); const directory = join(root, generationId); return { root, directory, projectsDirectory: join(directory, "projects"), manifest: join(directory, "manifest.json"), checkpoint: join(directory, "checkpoint.json"), report: join(directory, "report.json"), journal: join(directory, "publication-journal.json") }; }
export function migrationProjectPaths(generationId: string, localProjectId: string, homeDir?: string): MigrationProjectPaths { if (!SHA256.test(localProjectId)) throw new Error("invalid local project identity"); const directory = join(migrationGenerationPaths(generationId, homeDir).projectsDirectory, localProjectId); return { directory, sourceSnapshot: join(directory, "source.sqlite"), reverseDatabase: join(directory, "reverse.sqlite"), originalMainArchive: join(directory, "original-main.sqlite"), originalWalArchive: join(directory, "original-wal.sqlite"), nativeTranscriptSidecar: join(directory, "native-transcripts.jsonl"), passiveEventSidecar: join(directory, "passive-events.jsonl"), checkpointSidecar: join(directory, "remote-checkpoints.jsonl") }; }
export function createMigrationGeneration(homeDir?: string, generationId = randomUUID()): MigrationGenerationPaths { const paths = migrationGenerationPaths(generationId, homeDir); ensurePrivateDirectory(paths.root); mkdirSync(paths.directory, { mode: PRIVATE_DIRECTORY_MODE }); mkdirSync(paths.projectsDirectory, { mode: PRIVATE_DIRECTORY_MODE }); return paths; }
export function ensureMigrationProjectDirectory(generationId: string, localProjectId: string, homeDir?: string): MigrationProjectPaths { const paths = migrationProjectPaths(generationId, localProjectId, homeDir); ensurePrivateDirectory(paths.directory); return paths; }
function descriptor(path: string, root: string, maxBytes: number): number { if (!contained(root, path)) throw new Error("migration artifact is outside the generation root"); const fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW); try { const stat = fstatSync(fd); if (!stat.isFile() || stat.nlink !== 1 || (stat.mode & 0o777) !== PRIVATE_FILE_MODE) throw new Error("migration artifact is not a private single-link file"); if (stat.size > maxBytes) throw new Error("migration artifact exceeds the configured size limit"); return fd; } catch (error) { closeSync(fd); throw error; } }
export function readMigrationArtifact(path: string, root: string, maxBytes = MIGRATION_ARTIFACT_MAX_BYTES): string { if (!Number.isSafeInteger(maxBytes) || maxBytes < 0) throw new RangeError("maxBytes must be non-negative"); const fd = descriptor(path, root, maxBytes); try { const chunks: Buffer[] = []; let total = 0; const buffer = Buffer.allocUnsafe(Math.min(64 * 1024, maxBytes + 1)); while (total <= maxBytes) { const bytes = readSync(fd, buffer, 0, Math.min(buffer.length, maxBytes + 1 - total), null); if (bytes === 0) break; chunks.push(Buffer.from(buffer.subarray(0, bytes))); total += bytes; } if (total > maxBytes) throw new Error("migration artifact exceeds the configured size limit"); return Buffer.concat(chunks, total).toString("utf8"); } finally { closeSync(fd); } }
export function atomicWriteMigrationArtifact(path: string, content: string, root = dirname(path)): void { if (!contained(root, path)) throw new Error("migration artifact is outside the permitted root"); ensurePrivateDirectory(dirname(path)); const temporary = join(dirname(path), `.${basename(path)}.${randomBytes(12).toString("hex")}.tmp`); let fd: number | undefined; try { fd = openSync(temporary, constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW | constants.O_WRONLY, PRIVATE_FILE_MODE); fchmodSync(fd, PRIVATE_FILE_MODE); writeFileSync(fd, content, "utf8"); fsyncSync(fd); closeSync(fd); fd = undefined; if (existsSync(path)) { const current = lstatSync(path); if (!current.isFile() || current.isSymbolicLink() || current.nlink !== 1) throw new Error("refusing to replace an unsafe migration artifact"); } renameSync(temporary, path); const directoryFd = openSync(dirname(path), constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW); try { fsyncSync(directoryFd); } finally { closeSync(directoryFd); } } finally { if (fd !== undefined) closeSync(fd); rmSync(temporary, { force: true }); } }
export function fingerprintMigrationFileSync(path: string, root = dirname(path)): MigrationFileFingerprint { if (!contained(root, path)) throw new Error("fingerprint target is outside the permitted root"); const fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW); try { const before = fstatSync(fd); if (!before.isFile() || before.nlink !== 1) throw new Error("fingerprint target must be a regular single-link file"); const hash = createHash("sha256"); const buffer = Buffer.allocUnsafe(64 * 1024); for (;;) { const bytes = readSync(fd, buffer, 0, buffer.length, null); if (bytes === 0) break; hash.update(buffer.subarray(0, bytes)); } const after = fstatSync(fd); const current = statSync(path); if (after.dev !== before.dev || after.ino !== before.ino || after.size !== before.size || after.mtimeMs !== before.mtimeMs || current.dev !== before.dev || current.ino !== before.ino) throw new Error("fingerprint target changed while hashing"); return { path, device: before.dev, inode: before.ino, size: before.size, mtimeMs: before.mtimeMs, sha256: hash.digest("hex") }; } finally { closeSync(fd); } }
export async function fingerprintMigrationFile(path: string, root = dirname(path)): Promise<MigrationFileFingerprint> { return fingerprintMigrationFileSync(path, root); }
export function sameMigrationFingerprint(left: MigrationFileFingerprint | null, right: MigrationFileFingerprint | null): boolean { return left === null || right === null ? left === right : left.device === right.device && left.inode === right.inode && left.size === right.size && left.mtimeMs === right.mtimeMs && left.sha256 === right.sha256; }

const STATUSES: readonly MigrationStatus[] = ["planned", "dry-run-verified", "applying", "applied", "verified", "active", "rollback-ready", "rolled-back", "failed"];
function validFile(value: unknown): boolean { return record(value) && typeof value.path === "string" && Number.isSafeInteger(value.device) && Number.isSafeInteger(value.inode) && Number.isSafeInteger(value.size) && typeof value.mtimeMs === "number" && SHA256.test(String(value.sha256)); }
export function validateMigrationManifest(value: unknown): MigrationManifest { if (!record(value) || value.version !== MIGRATION_MANIFEST_VERSION || typeof value.generationId !== "string" || !GENERATION.test(value.generationId)) throw new Error("invalid migration manifest identity"); if (value.direction !== "sqlite-to-postgresql" || value.sourceBackend !== "sqlite" || value.destinationBackend !== "postgresql" || !STATUSES.includes(value.status as MigrationStatus)) throw new Error("invalid migration manifest state"); if (!timestamp(value.createdAt) || !timestamp(value.updatedAt) || !Number.isSafeInteger(value.batchSize) || (value.batchSize as number) <= 0 || !Number.isSafeInteger(value.sampleSize) || (value.sampleSize as number) <= 0 || !SHA256.test(String(value.schemaManifestSha256))) throw new Error("invalid migration manifest metadata"); if (!record(value.coverage) || !Array.isArray(value.projects) || value.projects.length === 0 || !record(value.protocol)) throw new Error("invalid migration manifest coverage"); for (const project of value.projects) { if (!record(project) || !record(project.identity) || typeof project.identity.localProjectId !== "string" || !SHA256.test(project.identity.localProjectId) || !Array.isArray(project.tables) || !record(project.operationalEvidence)) throw new Error("invalid migration project state"); if (project.sourceFingerprint !== null && (!record(project.sourceFingerprint) || !validFile(project.sourceFingerprint.main) || (project.sourceFingerprint.wal !== null && !validFile(project.sourceFingerprint.wal)))) throw new Error("invalid migration source fingerprint"); if (project.snapshot !== null && (!record(project.snapshot) || !validFile(project.snapshot.file))) throw new Error("invalid migration snapshot"); } return value as unknown as MigrationManifest; }
function parse(path: string, root: string): unknown { try { return JSON.parse(readMigrationArtifact(path, root)) as unknown; } catch (error) { throw new Error("migration artifact is not valid JSON", { cause: error }); } }
function write(path: string, value: unknown, root: string): void { atomicWriteMigrationArtifact(path, `${canonicalJson(value)}\n`, root); }
export function readMigrationManifest(generationId: string, homeDir?: string): MigrationManifest { const paths = migrationGenerationPaths(generationId, homeDir); return validateMigrationManifest(parse(paths.manifest, paths.directory)); }
export function writeMigrationManifest(manifest: MigrationManifest, homeDir?: string): void { const value = validateMigrationManifest(manifest); const paths = migrationGenerationPaths(value.generationId, homeDir); write(paths.manifest, value, paths.directory); }
export function manifestSha256(manifest: MigrationManifest): string { return sha256Canonical(validateMigrationManifest(manifest)); }
export function writeMigrationCheckpoint(manifest: MigrationManifest, homeDir?: string): MigrationCheckpoint { const value = validateMigrationManifest(manifest); const checkpoint: MigrationCheckpoint = { version: MIGRATION_MANIFEST_VERSION, generationId: value.generationId, manifestSha256: manifestSha256(value), updatedAt: value.updatedAt, projects: value.projects.map(({ identity, status, tables }) => ({ localProjectId: identity.localProjectId, status, tables })) }; const paths = migrationGenerationPaths(value.generationId, homeDir); write(paths.checkpoint, checkpoint, paths.directory); return checkpoint; }
export function writeMigrationReport(report: MigrationVerificationReport, homeDir?: string): void { if (report.version !== MIGRATION_MANIFEST_VERSION || !GENERATION.test(report.generationId)) throw new Error("invalid migration report"); const paths = migrationGenerationPaths(report.generationId, homeDir); write(paths.report, report, paths.directory); }
export function readPublicationJournal(generationId: string, homeDir?: string): MigrationPublicationJournal | null { const paths = migrationGenerationPaths(generationId, homeDir); if (!existsSync(paths.journal)) return null; const value = parse(paths.journal, paths.directory); if (!record(value) || value.version !== MIGRATION_MANIFEST_VERSION || value.generationId !== generationId || !Array.isArray(value.projects)) throw new Error("invalid publication journal"); return value as unknown as MigrationPublicationJournal; }
export function writePublicationJournal(generationId: string, journal: MigrationPublicationJournal, homeDir?: string): void { if (journal.generationId !== generationId) throw new Error("journal generation does not match"); const paths = migrationGenerationPaths(generationId, homeDir); write(paths.journal, journal, paths.directory); }
export function listMigrationManifests(homeDir?: string): MigrationManifest[] { const root = migrationsRoot(homeDir); if (!existsSync(root)) return []; const stat = lstatSync(root); if (!stat.isDirectory() || stat.isSymbolicLink() || (stat.mode & 0o777) !== PRIVATE_DIRECTORY_MODE) throw new Error("migration root must be a private directory"); return readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory() && GENERATION.test(entry.name)).map((entry) => readMigrationManifest(entry.name, homeDir)); }
export function generationRelativePath(generationId: string, path: string, homeDir?: string): string { const root = migrationGenerationPaths(generationId, homeDir).directory; if (!contained(root, path)) throw new Error("path is outside the migration generation"); return relative(root, path); }
